#!/usr/bin/env python3
"""pack_rom.py — OS-MOAP ROM packer: bundle -> deterministic tar.gz -> base64 -> notecards.

Emits rom/rom-000.txt (manifest) + rom-001.txt.. (data). Paste each file into a same-named
notecard in the prim (or flash via bot once notecard-write exists — P18).

Geometry is locked to the Phase-0 MEASURED ceilings (DESIGN.md), and the packer refuses
to emit anything over them:
  - notecard line  = 1024 base64 chars   (P17: no truncation <=1024B on the sync path;
                                          >1024 is UNTESTED — do not raise without a probe)
  - HTTP chunk     = 8 lines = 8192 chars ~= 8KB wire  (throttle: ~130KB burst, ~8KB/s
                                          refill PER URL; <=8KB/response doctrine)
  - notecard card  = 7 chunks = 56 lines ~= 57.3KB     (P16/P17: 60KB cards proven)
Chunks NEVER span cards, so the LSL reader's chunk->location math is two divisions:
  card = 1 + chunk // KPC ; first_line = (chunk % KPC) * LPK

Manifest (card rom-000) = compact JSON wrapped at LINE_CHARS-char lines (consumers join
all lines). Keys: v, enc, gz, lc (line chars), lpk (lines/chunk), kpc (chunks/card),
nl/nk/nc (lines/chunks/cards), rb/zb (raw tar / gzip bytes), bs (sha256 of tar.gz),
ks (per-chunk sha256[:16] over the chunk's base64 TEXT — hash-before-decode in stage-0),
f ([name, size] per bundled file).

Usage:
  python3 tools/pack_rom.py            # pack + verify + stats (default: everything)
  python3 tools/pack_rom.py --no-verify
"""
import argparse
import base64
import glob
import gzip
import hashlib
import io
import json
import os
import re
import subprocess
import sys
import tarfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # OS-MOAP/

LINE_CHARS = 1024        # P17 measured ceiling (chars == bytes: base64 is ASCII)
LINES_PER_CHUNK = 8      # 8192 chars/chunk ~= 8KB wire per /rom response
CHUNKS_PER_CARD = 7      # 56 lines = 57,344 chars per data card
CARD_MAX_BYTES = 60_000  # P16/P17: 60KB cards paste + sync-read fine
HTTP_CHUNK_MAX = 12_288  # P1: largest response actually served; hard refusal above

# bundle v1: (source path relative to OS-MOAP/, archive name)
BUNDLE_V1 = [
    ('guest/busybox-v0.wasm',            'busybox.wasm'),
    ('web/vendor/xterm.js',              'web/xterm.js'),
    ('web/vendor/xterm.css',             'web/xterm.css'),
    ('build/stage1.js',                  'web/stage1.js'),  # generated below
    ('guest/busybox/upstream/LICENSE',   'LICENSE'),        # GPLv2 hygiene
    ('guest/rootfs/etc/motd',            'rootfs/etc/motd'),
    ('guest/rootfs/etc/profile',         'rootfs/etc/profile'),
    ('guest/rootfs/etc/apk/repositories', 'rootfs/etc/apk/repositories'),
    ('guest/rootfs/home/user/.profile',  'rootfs/home/user/.profile'),
]

APPLET_TABLES = 'guest/busybox/upstream/include/applet_tables.h'  # generated by build.sh


def bin_markers():
    """Empty rootfs/bin/<applet> marker files, one per applet in the ACTUAL build
    (parsed from the generated applet table, so it can't drift). They make `ls /bin`
    look like a real system and give lineedit's path completion something to scan;
    FEATURE_PREFER_APPLETS means execution never touches them."""
    src = open(os.path.join(ROOT, APPLET_TABLES)).read()
    block = re.search(r'applet_names\[\][^=]*=\s*""\s*(.*?);', src, re.S)
    names = re.findall(r'"([a-z0-9_\[\.-]+)"\s*"\\0"', block.group(1))
    if not names:
        sys.exit('pack_rom: no applet names parsed from ' + APPLET_TABLES)
    return [('__EMPTY__', f'rootfs/bin/{n}') for n in sorted(set(names))]


# stage1.js = fs.mjs + shim.mjs stripped of module syntax + term.js (already classic).
# Stage-0 has no way to load ES modules from tar bytes (blob-module relative imports
# don't resolve), so ROM ships a classic script that hangs everything on window.OSD.
STAGE1_MODULES = ['web/wasi/fs.mjs', 'web/wasi/shim.mjs', 'web/wasi/spawn.mjs', 'web/wasi/pkg.mjs']  # order matters: shim uses fs, spawn uses shim
STAGE1_CLASSIC = 'web/term.js'


def unmodule(src):
    """Strip the narrow ES-module dialect OUR files use (top-level import lines,
    `export <decl>`). Not a general transpiler — verify() smoke-runs the result."""
    out = []
    for line in src.splitlines():
        if line.startswith('import '):
            continue
        out.append(re.sub(r'^export (function|class|const|let|var) ', r'\1 ', line))
    return '\n'.join(out)


def build_stage1():
    parts = ['// GENERATED by tools/pack_rom.py — do not edit. Classic-script stage-1',
             '// bundle: web/wasi/fs.mjs + web/wasi/shim.mjs (module syntax stripped) +',
             '// web/term.js. Exports land on globalThis.OSD.',
             '(function () {']
    for rel in STAGE1_MODULES:
        with open(os.path.join(ROOT, rel)) as f:
            parts.append(unmodule(f.read()))
    parts.append('var OSD = (globalThis.OSD = globalThis.OSD || {});')
    parts.append('OSD.createShim = createShim; OSD.ExitError = ExitError;')
    parts.append('OSD.buildTree = buildTree; OSD.FILETYPE = FILETYPE;')
    parts.append('OSD.makeSpawner = makeSpawner; OSD.makePkgService = makePkgService;')
    parts.append('})();')
    with open(os.path.join(ROOT, STAGE1_CLASSIC)) as f:
        parts.append(f.read())
    os.makedirs(os.path.join(ROOT, 'build'), exist_ok=True)
    out = os.path.join(ROOT, 'build', 'stage1.js')
    with open(out, 'w') as f:
        f.write('\n'.join(parts))
    return out


def smoke_stage1(path):
    """Run the generated classic bundle under node: it must define OSD.* and produce a
    working shim (catches anything unmodule() mangled)."""
    js = ("globalThis.window = globalThis;"
          "eval(require('fs').readFileSync(process.argv[1], 'utf8'));"
          "const s = OSD.createShim({ root: OSD.buildTree({}) });"
          "if (!s.imports || !OSD.bootTerminal || !OSD.ExitError) throw new Error('OSD incomplete');"
          "console.log('stage1 smoke OK');")
    r = subprocess.run(['node', '-e', js, path], capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f'pack_rom: stage1 smoke test FAILED:\n{r.stderr}')
    return r.stdout.strip()


def build_tar(files):
    """Deterministic ustar: sorted by arcname, mtime=0, uid/gid 0, mode 0644, no dir entries."""
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode='w', format=tarfile.USTAR_FORMAT) as tf:
        for src, arc in sorted(files, key=lambda e: e[1]):
            if src == '__EMPTY__':
                data = b''
            else:
                with open(os.path.join(ROOT, src), 'rb') as f:
                    data = f.read()
            ti = tarfile.TarInfo(arc)
            ti.size = len(data)
            ti.mtime = 0
            ti.mode = 0o644
            ti.uid = ti.gid = 0
            ti.uname = ti.gname = ''
            tf.addfile(ti, io.BytesIO(data))
    return buf.getvalue()


def wrap(text, width):
    return [text[i:i + width] for i in range(0, len(text), width)]


def pack(outdir):
    print(smoke_stage1(build_stage1()))
    for src, _ in BUNDLE_V1:
        if not os.path.exists(os.path.join(ROOT, src)):
            sys.exit(f'pack_rom: missing bundle source {src}')

    bundle = BUNDLE_V1 + bin_markers()
    raw = build_tar(bundle)
    gz = gzip.compress(raw, compresslevel=9, mtime=0)
    b64 = base64.b64encode(gz).decode('ascii')

    chunk_chars = LINE_CHARS * LINES_PER_CHUNK
    if chunk_chars > HTTP_CHUNK_MAX:
        sys.exit(f'pack_rom: chunk {chunk_chars} chars exceeds measured HTTP ceiling {HTTP_CHUNK_MAX}')

    lines = wrap(b64, LINE_CHARS)
    chunks = wrap(b64, chunk_chars)
    lines_per_card = LINES_PER_CHUNK * CHUNKS_PER_CARD
    cards = [lines[i:i + lines_per_card] for i in range(0, len(lines), lines_per_card)]
    card_bytes = max(sum(len(l) + 1 for l in c) for c in cards)  # +1/line: newline on paste
    if card_bytes > CARD_MAX_BYTES:
        sys.exit(f'pack_rom: card would be {card_bytes}B > measured ceiling {CARD_MAX_BYTES}')

    manifest = {
        'v': 1, 'enc': 'b64', 'gz': 1,
        'lc': LINE_CHARS, 'lpk': LINES_PER_CHUNK, 'kpc': CHUNKS_PER_CARD,
        'nl': len(lines), 'nk': len(chunks), 'nc': len(cards),
        'rb': len(raw), 'zb': len(gz),
        'bs': hashlib.sha256(gz).hexdigest(),
        'ks': [hashlib.sha256(k.encode('ascii')).hexdigest()[:16] for k in chunks],
        # 'f' lists the real payload files only (informational); the ~30 empty
        # rootfs/bin/<applet> completion markers would just be noise here
        'f': [[arc, os.path.getsize(os.path.join(ROOT, src))] for src, arc in
              sorted(BUNDLE_V1, key=lambda e: e[1])],
    }
    mjson = json.dumps(manifest, separators=(',', ':'))
    mlines = wrap(mjson, LINE_CHARS)
    if sum(len(l) + 1 for l in mlines) > CARD_MAX_BYTES:
        sys.exit('pack_rom: manifest exceeds one card — shard it (not expected at v1 sizes)')

    os.makedirs(outdir, exist_ok=True)
    for stale in glob.glob(os.path.join(outdir, 'rom-[0-9][0-9][0-9].txt')):
        os.remove(stale)
    with open(os.path.join(outdir, 'rom-000.txt'), 'w') as f:
        f.write('\n'.join(mlines) + '\n')
    for ci, card in enumerate(cards, start=1):
        with open(os.path.join(outdir, f'rom-{ci:03d}.txt'), 'w') as f:
            f.write('\n'.join(card) + '\n')
    return manifest, b64


def verify(outdir, manifest):
    """Round-trip: re-read the emitted cards exactly as the LSL reader + stage-0 would."""
    with open(os.path.join(outdir, 'rom-000.txt')) as f:
        m = json.loads(''.join(f.read().splitlines()))
    assert m == manifest, 'manifest re-read mismatch'

    lines = []
    for ci in range(1, m['nc'] + 1):
        with open(os.path.join(outdir, f'rom-{ci:03d}.txt')) as f:
            card_lines = f.read().splitlines()
        assert all(len(l) <= m['lc'] for l in card_lines), f'card {ci}: line over lc'
        lines.extend(card_lines)
    assert len(lines) == m['nl'], f'line count {len(lines)} != nl {m["nl"]}'

    b64 = ''.join(lines)
    chunks = wrap(b64, m['lc'] * m['lpk'])
    assert len(chunks) == m['nk'], 'chunk count mismatch'
    for i, k in enumerate(chunks):
        assert hashlib.sha256(k.encode()).hexdigest()[:16] == m['ks'][i], f'chunk {i} sha mismatch'
        # chunk -> (card, line) mapping the LSL reader will use
        card = 1 + i // m['kpc']
        first = (i % m['kpc']) * m['lpk']
        with open(os.path.join(outdir, f'rom-{card:03d}.txt')) as f:
            cl = f.read().splitlines()
        assert ''.join(cl[first:first + m['lpk']]) == k, f'chunk {i} card/line map mismatch'

    gz = base64.b64decode(b64)
    assert hashlib.sha256(gz).hexdigest() == m['bs'], 'bundle sha mismatch'
    raw = gzip.decompress(gz)
    assert len(raw) == m['rb'], 'raw size mismatch'
    with tarfile.open(fileobj=io.BytesIO(raw)) as tf:
        for src, arc in BUNDLE_V1 + bin_markers():
            got = tf.extractfile(arc).read()
            want = b'' if src == '__EMPTY__' else open(os.path.join(ROOT, src), 'rb').read()
            assert got == want, f'{arc}: content mismatch vs {src}'
    return True


def stats(m):
    wire_kb = m['nl'] * LINE_CHARS / 1024
    n_caps = 3
    per_cap_rate = 6.0  # KB/s, throttle-safe pace (refill is ~8KB/s)
    stream_s = wire_kb / (n_caps * per_cap_rate)
    print(f'bundle: {m["rb"]:,}B tar -> {m["zb"]:,}B gz -> {m["nl"] * LINE_CHARS:,} b64 chars')
    print(f'layout: {m["nk"]} chunks x {LINE_CHARS * LINES_PER_CHUNK} chars, '
          f'{m["nc"]} data cards (+1 manifest), {m["nl"]} lines')
    print(f'files : ' + ', '.join(f'{n} ({s:,}B)' for n, s in m['f']))
    print(f'boot  : ~{wire_kb:.0f}KB wire; {n_caps} caps @ {per_cap_rate:.0f}KB/s '
          f'-> ~{stream_s:.0f}s stream + ~8s card warm-up (parallel) = '
          f'~{stream_s + 8:.0f}s cold boot (warm boot: IndexedDB, no streaming)')
    print(f'sha   : {m["bs"]}')


def emit_page(outdir):
    """stage-0 as a notecard (page-000): the page outgrew script memory — a 19KB string
    + its own constant table in one 64KB Mono script = Stack-Heap Collision (in-world).
    Core sync-reads this card and serves it; lines minified (full-line comments/blanks
    dropped, indent stripped) and validated <=1024B (P17)."""
    src = open(os.path.join(ROOT, 'web', 'stage0.html')).read().splitlines()
    lines = []
    for raw in src:
        line = raw.strip()
        if not line or line.startswith('//'):
            continue
        if len(line.encode()) > 1024:
            sys.exit(f'pack_rom: page line over 1024B: {line[:60]}...')
        lines.append(line)
    with open(os.path.join(outdir, 'page-000.txt'), 'w') as f:
        f.write('\n'.join(lines) + '\n')
    return len(lines), sum(len(l) + 1 for l in lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--out', default=os.path.join(ROOT, 'rom'))
    ap.add_argument('--no-verify', action='store_true')
    args = ap.parse_args()

    manifest, _ = pack(args.out)
    if not args.no_verify:
        verify(args.out, manifest)
        print('verify: PASS (cards -> chunks -> shas -> gunzip -> untar -> byte-identical)')
    pn, pb = emit_page(args.out)
    print(f'page  : page-000.txt {pn} lines, {pb}B (stage-0 served from notecard, not script)')
    stats(manifest)


if __name__ == '__main__':
    main()
